services:
  tikettera_app:
    container_name: tikettera_app
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    restart: on-failure
    environment:
      XDEBUG_CONFIG: "remote_enable=1 remote_autostart=1 remote_port=9000"
      XDEBUG_KEY: pub
      PHP_IDE_CONFIG: "serverName=DOCKER"
    expose:
      - 9000
    volumes:
      - type: bind
        source: ./server
        target: /usr/src/app
        consistency: delegated
      - ~/.ssh:/root/.ssh:ro
      - ~/.composer:/root/.composer
      - ./docker/php/laravel.ini:/usr/local/etc/php/conf.d/laravel.ini
    depends_on:
      - tikettera_db
    networks:
      tikettera_network:
        ipv4_address: 172.16.0.2
  tikettera_node:
    container_name: tikettera_node
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    restart: always
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - FAST_REFRESH=true
    stdin_open: true
    tty: true
    ports:
      - "4201:4200"
    volumes:
      - type: bind
        source: .
        target: /app
        consistency: delegated
    networks:
      tikettera_network:
        ipv4_address: 172.16.0.7
  tikettera_nginx:
    container_name: tikettera_nginx
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
      - type: bind
        source: ./server/public
        target: /usr/src/app
        consistency: delegated
    ports:
      - "86:80"
    depends_on:
      - tikettera_app
    environment:
      NGINX_FPM_HOST: tikettera_app
      NGINX_ROOT: /usr/src/app/public
    networks:
      tikettera_network:
          ipv4_address: 172.16.0.3
  tikettera_db:
    image: mysql:8.0
    container_name: tikettera_db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: tikettera
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: tikettera
      MYSQL_PASSWORD: 1234
    ports:
      - "33060:3306"
    volumes:
      - tikettera_db_data:/var/lib/mysql
    networks:
      tikettera_network:
        ipv4_address: 172.16.0.4
  tikettera_phpmyadmin:
    container_name: tikettera_phpmyadmin
    image: phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - tikettera_db
    networks:
      tikettera_network:
          ipv4_address: 172.16.0.5
  tikettera_redis:
    container_name: tikettera_redis
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - tikettera_redis_data:/data
    networks:
      tikettera_network:
          ipv4_address: 172.16.0.6
  tikettera_mailhog:
    platform: linux/x86_64
    image: mailhog/mailhog
    container_name: tikettera_mailhog
    logging:
      driver: 'none'
    ports:
      - 30250:8025
    networks:
      tikettera_network:
          ipv4_address: 172.16.0.8
  tikettera_minio:
    image: minio/minio
    container_name: tikettera_minio
    command: server /data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: tikettera
      MINIO_ROOT_PASSWORD: tikettera
    volumes:
      - tikettera_minio_data:/data
      - ./docker/minio/init:/docker-entrypoint-init.d
    networks:
      tikettera_network:
        ipv4_address: 172.16.0.9


volumes:
  tikettera_db_data:
    external: true
  tikettera_redis_data:
    external: true
  tikettera_minio_data:
    external: true

networks:
  tikettera_network:
    external: true
    name: tikettera_network
